ecomm/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('products/',
         include(('products.urls', 'products'), namespace='products')),
    path('api/', include(('rest_api.urls', 'rest_api'), namespace='rest_api'))
]

products/urls.py
from django.urls import path

from products import views

urlpatterns = [
    path('list', views.list_products, name='list'),
    path('create', views.create_product, name='create'),
    path('delete/<int:product_id>', views.delete_product, name='delete'),
    path('update/<int:product_id>', views.update_product, name='update')
]

rest_api/urls.py
from django.urls import include, path, re_path

from rest_framework.authtoken.views import obtain_auth_token

from rest_framework import routers

from rest_api import views

router = routers.DefaultRouter()
router.register(r'products', views.ProductApiViewSet)

urlpatterns = [
    path('', include(router.urls)),
    path('categories/', views.CategoryListOnlyAPIView.as_view()),
    re_path(r'vendas/(?P<pk>\d+)?', views.OrderAPIView.as_view()),
    path('get_token', obtain_auth_token)
    # username e um password
]

products/models.py
"""
    Modelos do app de Produtos.
"""
from django.db import models
from django.db.models import Q, QuerySet


# Create your models here.

class ProductManager(models.Manager):
    def with_text(self, text: str) -> QuerySet:
        """
            Realiza a pesquisa nos produtos cujo nome contenha **text**.

            :param text: Texto que será usado na pesquisa

            :return: QuerySet com o filtro aplicado
        """
        queryset = self.get_queryset().filter(name__contains=text)
        return queryset

    def expensive_products(self) -> QuerySet:
        """
            Realiza o filtro dos produtos cujo preço seja maior do que 500,00 R$.

            :return: QuerySet com o filtro aplicado
        """
        # Executa a queryset com o filtro maior ou igual a 500
        return self.get_queryset().filter(price__gte=500)

    def cheap_toys(self) -> QuerySet:
        """
            Retorna a lista com os brinquedos mais baratos.

            :return: QuerySet com o filtro aplicado
        """
        return self.get_queryset().filter(
            category__name='Brinquedos',
            price__lte=100
        )

    def toys_or_expensive_items(self) -> QuerySet:
        """
            Retorna a lista com os brinquedos mais caros.

            :return: QuerySet com o filtro aplicado
        """
        query_filter = Q(category__name='Brinquedos') | Q(price__gte=500)
        queryset = self.get_queryset().filter(query_filter)
        print(queryset.query)
        return queryset

    def test_function(self):
        a = self.with_text("")
        b = self.expensive_products()
        c = self.cheap_toys()
        d = self.toys_or_expensive_items()


class Category(models.Model):
    name = models.CharField('Nome', max_length=50)
    description = models.TextField('Descrição')

    def __str__(self):
        return f'{self.name} - {self.products.count()}'

    class Meta:
        verbose_name_plural = 'Categories'


class Product(models.Model):
    """
        Model contendo todos os campos necessários para cadastrar produtos no
        ecomm.
    """
    objects = ProductManager()
    name = models.CharField('Nome', max_length=100)
    description = models.TextField('Descrição')
    price = models.DecimalField('Preço', max_digits=8, decimal_places=2)
    category = models.ForeignKey(
        Category,
        on_delete=models.deletion.DO_NOTHING,
        related_name='products'
    )

    def __str__(self):
        return self.name


class Order(models.Model):
    name = models.CharField('Nome do Cliente', max_length=100)
    payment = models.CharField('Meio Pagamento', max_length=50)
    products = models.ManyToManyField(Product)

    @property
    def total_amount(self):
        return sum([product.price for product in self.products.all()])

    def __str__(self):
        return f'{self.name} - {self.total_amount}'

rest_api/models.py
from django.db import models

# Create your models here.

products/forms.py
from django import forms

from products.models import Product


class ProductModelForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ['name', 'price', 'description', 'category']

products/views.py
from django.shortcuts import render, redirect
from django.conf import settings

from products.models import Product
from products.forms import ProductModelForm

# Create your views here.

def list_products(request):
    products = Product.objects.all()

    context = {
        'products': products,
        'products_empty': []
    }

    return render(request, 'products/list.html', context=context)


def create_product(request):
    if request.method == 'POST':
        # Salvar form
        form = ProductModelForm(request.POST)
        if form.is_valid():
            # True -> é valido
            form.save()
            return redirect('products:list')
    else:
        # Get form
        form = ProductModelForm()

    context = {
        'form': form
    }
    return render(request, 'products/create.html', context=context)


def delete_product(request, product_id):
    product = Product.objects.get(pk=product_id)
    product.delete()
    return redirect('products:list')


def update_product(request, product_id):
    product = Product.objects.get(pk=product_id)

    if request.method == 'POST':
        # salvar form
        form = ProductModelForm(data=request.POST, instance=product)
        if form.is_valid():
            form.save()
            return redirect('products:list')
    else:
        # GET
        form = ProductModelForm(instance=product)

    context = {
        'form': form,
    }

    return render(request, 'products/update.html', context=context)

rest_api/views.py
from django.shortcuts import render

from rest_framework import viewsets
from rest_framework import mixins
from rest_framework import generics
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework import status
from rest_framework.authentication import TokenAuthentication
from rest_framework.permissions import IsAuthenticated

from rest_api.api_permissions import OnlyAdminCanCreate
from rest_api.serializers import (
    ProductModelSerializer,
    CategoryModelSerializer,
    OrderModelSerializer
)
from products.models import Product, Category, Order

# Create your views here.

class ProductApiViewSet(viewsets.ModelViewSet):
    queryset = Product.objects.all()
    serializer_class = ProductModelSerializer


class CategoryListOnlyAPIView(mixins.ListModelMixin, generics.GenericAPIView):
    queryset = Category.objects.all()
    serializer_class = CategoryModelSerializer

    def get(self, request, *args, **kwargs):
        # validation
        return self.list(request, *args, **kwargs)


class OrderAPIView(APIView):
    authentication_classes = [TokenAuthentication]
    permission_classes = [IsAuthenticated, OnlyAdminCanCreate]

    def post(self, request, pk, format=None):
        serializer = OrderModelSerializer(data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data, status=status.HTTP_201_CREATED)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

    def get(self, request, pk, format=None):
        if not pk:
            orders = Order.objects.all()
            serializer = OrderModelSerializer(orders, many=True)
        else:
            order = Order.objects.get(pk=pk)
            serializer = OrderModelSerializer(order)

        return Response(serializer.data)

products/templates/base.html
{% load static %}
<html>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>AceleraDev Codenation - {% block title %}2019{% endblock %}</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/custom.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/font-awesome.min.css' %}">
    {% block custom_css %}{% endblock %}
    <body class="container">
        <nav class="navbar navbar-expand-lg navbar-light" style="background-color: #e3f2fd;">
            <a class="navbar-brand" href="#">Ecomm</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'products:list' %}">Produtos</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="">Categorias</a>
                    </li>
                </ul>
            </div>
        </nav>
        <div id="content" class="container">
            {% block content %}{% endblock %}
        </div>
        <div class="card bg-dark text-white text-center">
            <div class="card-body">
                <span class="">AceleraDev Python e Django</span>
            </div>
        </div>
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
        <script src="{% static 'js/bootstrap.min.js' %}"></script>
        {% block custom_js %}{% endblock %}
    </body>
</html>

products/templates/products/create.html
{% extends "base.html" %}

{% block content %}
    <div class="row">
        <div class="col-md-9">
            <h2>Adicionar Produto</h2>
        </div>
    </div>
    <form method="post">
        {% csrf_token %}

        {% for field in form %}
            <div class="form-group row">
                <label for="{{ field.id_for_label }}" class="col-sm-2 col-form-label">{{ field.label }}</label>
                <div class="col-sm-10 ">
                    {{ field }}
                </div>
            </div>
            {% if field.errors %}
                {% for error in field.errors %}
                    <div class="offset-sm-2 col-sm-10">
                        <span class="badge badge-pill badge-danger">{{ error }}</span>
                    </div>
                {% endfor %}
            {% endif %}
        {% endfor %}
        <div class="row justify-content-end">
            <div class="col-md-2">
                <button class="btn btn-primary btn-block" type="submit">Salvar</button>
            </div>
        </div>
    </form>
{% endblock %}

products/templates/products/list.html
{% extends "base.html" %}

{% block content %}

    <div class="row">
        <div class="col-md-9">
            <h2>Listagem de Produtos</h2>
        </div>
        <div class="col-md-3">
            <a class="btn btn-primary btn-block" href="{% url 'products:create' %}"><i class="fa fa-plus-circle"></i> Adicionar Produto</a>
        </div>
        <table class="table table-striped table-bordered">
            <thead>
                <tr>
                    <th>Nome</th>
                    <th>Preço</th>
                    <th>Descrição</th>
                    <th>Categoria</th>
                    <th>Ações</th>
                </tr>
            </thead>
            <tbody>
                {% for product in products %}
                    <tr>
                        <td>{{ product.name|capfirst }}</td>
                        <td>{{ product.price }} R$</td>
                        <td>{{ product.description }}</td>
                        <td>{{ product.category.name }}</td>
                        <td>
                            <div class="btn-group" role="group" aria-label="Basic example">
                                <a href="{% url 'products:update' product.pk %}" class="btn btn-warning"><i class="fas fa-edit"></i></a>
                                <a href="{% url 'products:delete' product.pk %}" class="btn btn-danger"><i class="fas fa-trash-alt"></i></a>
                            </div>
                        </td>
                    </tr>
                {% empty %}
                    <tr>
                        <td colspan=5 class="text-center">
                            Não Há produtos para serem listados
                        </td>
                    </tr>
                {% endfor %}
            </body>
        </table>
    </div>
{% endblock %}

products/templates/products/update.html
{% extends "base.html" %}

{% block content %}
    <div class="row">
        <div class="col-md-9">
            <h2>Atualizar Produto</h2>
        </div>
    </div>
    <form method="post">
        {% csrf_token %}

        {% for field in form %}
            <div class="form-group row">
                <label for="{{ field.id_for_label }}" class="col-sm-2 col-form-label">{{ field.label }}</label>
                <div class="col-sm-10 ">
                    {{ field }}
                </div>
            </div>
            {% if field.errors %}
                {% for error in field.errors %}
                    <div class="offset-sm-2 col-sm-10">
                        <span class="badge badge-pill badge-danger">{{ error }}</span>
                    </div>
                {% endfor %}
            {% endif %}
        {% endfor %}
        <div class="row justify-content-end">
            <div class="col-md-2">
                <button class="btn btn-primary btn-block" type="submit">Salvar</button>
            </div>
        </div>
    </form>
{% endblock %}